### ISSUE TITLE
Your site's "gatsby-node.js" must set the page path?

### ISSUE THREAD

**Issue by TDHTTTT** [v4iv/theleakycauldronblog#113]
Thanks for the good work! However, when I try to build the website using `gatsby build`. I have the following error:

``` bash
success open and validate gatsby-configs - 0.015 s
success load plugins - 9.831 s
success onPreInit - 0.027 s
success initialize cache - 0.113 s
success copy gatsby files - 1.932 s
success onPreBootstrap - 0.058 s
success source and transform nodes - 1.862 s
success building schema - 2.307 s
warn code block or inline code language not specified in markdown. applying generic code block
Your site's "gatsby-node.js" must set the page path when creating a page
⠀
{ path: '',
  component: '/.../theleakycauldronblog/src/templates/index.js',
  context:
   { group: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
     pathPrefix: '',
     first: true,
     last: false,
     index: 1,
     pageCount: 3,
     additionalContext: {} } }
error See the documentation for createPage https://www.gatsbyjs.org/docs/actions/#createPage
⠦ createPages
[======                      ]   3.985 s 16/73 22% Generating image thumbnails
```

Maybe that's something really basic which I oversees?

**Comment by TDHTTTT** [comment]
BTW, my developing environment is:
```bash
$ node --version
v10.15.2
$ npm --version
5.8.0
$ gatsby --version
2.7.0
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
```

**Comment by TDHTTTT** [comment]
I found a workaround by specify the pathPrefix explicitly:  `pathPrefix: '/'`. I am curious how it works for you.

**Comment by v4iv** [comment]
@TDHTTTT what's your pathPrefix parameter in config.js file?

**Comment by TDHTTTT** [comment]
Hi @v4iv ,

At first I tried 'blog' and it works but since I don't want any prefix, I set it to be '/'. So it seems to me as long as the pathPrefix is not empty, the `createPaginatedPages` will work.

But the case is not true on Netlify. So I wonder it might be a version problem.

**Comment by v4iv** [comment]
as you can see the default pathPrefix in config file is set to '/' for this exact reason, I don't see where pathPrefix was left blank in the repository?

**Comment by v4iv** [comment]
as you can see the default is already set to '/' I'll be closing the issue
