### ISSUE TITLE
Intergrate Algolia instead of Elastic-Lunr

### ISSUE THREAD

**Issue by h1eutran** [v4iv/theleakycauldronblog#149]
I want to try to integrate algolia instead of Elastic-Lunr but I'm not sure how

**Comment by v4iv** [comment]
Hey @GuillouTran did you take a look at this - https://www.gatsbyjs.org/docs/adding-search-with-algolia/

**Comment by h1eutran** [comment]
Yeah but I'm a student and I'm not very used to Gatsby. may you help me?

**Comment by v4iv** [comment]
Hmm, So you are in it for learning, I'm guessing.
From what I saw in your repositories, you seem to have no prior projects related to React or basic Gatsby or even plain JavaScript. You need to first learn basics of JavaScript along with basics of NPM, then learn React JS(not just syntax, at least make a few basic web apps using React), before even you can even begin to think of jumping in Gatsby JS.

Gatsby is new and fairly complicated for anyone trying to directly learn it without first learning basic JS and React. It also uses GraphQL which is fairly new as well. So once you are done learning making basic web apps with React, then you can do the tutorial from gatsbyjs.org.

In case you already know and have done all of the above already, I'd say try to follow through the tutorial and make a separate project using Algolia, first. If you run into a specific problem do let me know.
