### ISSUE TITLE
Field "image" must not have a selection since type "String" has no subfields.

### ISSUE THREAD

**Issue by mkassm** [v4iv/theleakycauldronblog#267]
Hey, I just created a project with Gatsby CLI from your repo, but when I run it locally it gives me two errors
`Field "image" must not have a selection since type "String" has no subfields.`
`Field "cover" must not have a selection since type "String" has no subfields.`
And here is the full error message

```

There was an error in your GraphQL query:

      Field "image" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" make sure that your input source 
and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\templates\about-page.js:130:13


 ERROR #85922  GRAPHQL

There was an error in your GraphQL query:

      Field "cover" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "cover". If you didn't expect "cover" to be of type "String" make sure that your input source 
and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\templates\article-page.js:91:13
```

I spend a lot of time on GATSBY Github issues and read a lot of solutions that didn't work for me, also read your [blog article](https://theleakycauldronblog.com/blog/problems-with-gatsby-image-and-their-workarounds) but also didn't work

So what I had tried
* Delete `.cache`, `node_modules` and reinstall them
* Ensure that all images already exist and read from the correct path and spelling mistakes
* Make sure of plugins order in `gatsby-config.js` file
* Add `fmImagesToRelative(node)` line in `gatsby-node.js` file

I can't find where is the problem, so hope you find that issue

## Update
after searching a lot, I figure out that I should deploy it in Netlify and control everything in the blog from CMS, after applying some [Netlify-CMS](https://www.gatsbyjs.com/tutorial/blog-netlify-cms-tutorial) configurations from /admin `config.yml` file and customizing the blog from the `config.js` file and other Gatsby files

Now, I'm trying to run it locally

**Comment by v4iv** [comment]
hey, sorry for the late reply, any update?

**Comment by mkassm** [comment]
Hello, thanks for your reply.
Unfortunately, I still have these two errors when I try to develop them locally

**Comment by v4iv** [comment]
I have run into similar problems earlier(in another project) and it turned out to be just Gatsby and Netlify CMS not playing well with my environment i.e. MacOS version, Node version, global installs etc and there was nothing I could do about it until eventually it went away with package updates (and once by figuring out a missing peer dependency that for some reason didn't get installed). My suggestion is to delete `lock file` and `node_modules` and try a different package manager (for e.g. if you are using yarn try npm and vice versa)

**Comment by mkassm** [comment]
Hey, sorry for late and thanks for your reply, appreciate that

I have already tried this solution but it cannot solve the problem and still, these two errors appears.

### Steps to reproduce
This repo is setup to recreate the error: [aboelkassem/blog](https://github.com/aboelkassem/blog)

1- clone the repo
2- run `npm install` or `yarn install`
3- run `gatsby develop` to see if it works locally fine or not
